config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/purchase_history', to: 'purchase_histories#index'
  get '/purchase_history/range', to: 'purchase_histories#range'
  # get '/purchase_history/:id', to: 'purchase_histories#show'

  post '/carts/add', to: 'carts#add'
  resources :carts, only: [:index, :edit, :update, :destroy]

  resources :products, only: [:show, :new, :create, :edit, :update, :destroy]
  
  resource :charge, only: [:create]
  
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
  belongs_to :user
  has_many :purchase_history_products, dependent: :destroy
  has_many :products, through: :purchase_history_products
end

app/controllers/purchase_histories_controller.rb
class PurchaseHistoriesController < ApplicationController
  before_action :exist_purchase_history
  def index
    if current_user.admin?
      @purchase_histories = PurchaseHistoryProduct.all.page(params[:page]).per(25).order('updated_at DESC')
      respond_to do |format|
        format.html
        format.csv do
          histories_csv
        end
      end
    else
      @purchase_histories = current_user.purchase_history.purchase_history_products.page(params[:page]).per(25).order('updated_at DESC')
    end
  end

  def range
    if current_user.admin?
      if Date.valid_date?(params["start_date(1i)"]&.to_i, params["start_date(2i)"]&.to_i, params["start_date(3i)"]&.to_i) \
        && Date.valid_date?(params["end_date(1i)"]&.to_i, params["end_date(2i)"]&.to_i, params["end_date(3i)"]&.to_i)
      
        start_date = Date.new(params["start_date(1i)"]&.to_i, params["start_date(2i)"]&.to_i, params["start_date(3i)"]&.to_i)
        end_date = Date.new(params["end_date(1i)"]&.to_i, params["end_date(2i)"]&.to_i, params["end_date(3i)"]&.to_i)

        unless start_date <= end_date
          flash[:success] = "終了日を開始日より後の日付にしてください。"
          @purchase_histories = PurchaseHistoryProduct.all.page(params[:page]).per(25).order('updated_at DESC')
        else
          range = start_date.beginning_of_day..end_date.end_of_day
          @purchase_histories = PurchaseHistoryProduct.where(updated_at: range).page(params[:page]).per(25).order('updated_at DESC')
        end

        respond_to do |format|
          format.html
          format.csv do
            histories_csv
          end
        end
      else
        @purchase_histories = PurchaseHistoryProduct.all.page(params[:page]).per(25).order('updated_at DESC')
        flash[:success] = "存在する日付を選択して下さい。"
      end
    else
      @purchase_histories = current_user.purchase_history.purchase_history_products.page(params[:page]).per(25).order(updated_at: "DESC")
    end
  end

  private

  def exist_purchase_history
    unless current_user.admin?
      unless current_user.purchase_history
        @products = Product.all
        flash[:success] = "購入履歴はありません"
        redirect_to root_path
      end
    end
  end

  def histories_csv
    current_time = Time.current.to_time.strftime('%Y%m%d%H%M')

    year = current_time[0..3]
    month = current_time[4..5]
    day = current_time[6..7]
    hour = current_time[8..9]
    minute = current_time[10..11]

    csv_date = CSV.generate do |csv|
      csv << ["#{year}年#{month}月#{day}日#{hour}時#{minute}分_注文履歴"]
      csv << []
      csv_column_names = ["注文者", "商品名", "購入数", "金額", "	配達者ID", "購入日"]
      csv << csv_column_names
      @purchase_histories.each do |info|
        csv_column_values = [
          info.user_name,
          info.product_name,
          info.quantity,
          info.price,
          info.delivery_user.to_s,
          info.updated_at.strftime('%Y/%m/%d %H:%M')
        ]
        csv << csv_column_values
      end
    end
    send_data(csv_date,filename: "#{current_time}_Purchase_History.csv")
  end
end

app/helpers/purchase_histories_helper.rb
module PurchaseHistoriesHelper
end

app/views/purchase_histories/_csv.html.erb
<div class="col-md-8 offset-md-2">
  <h2 class="text-center">注文履歴</h2>


  <% if current_user.admin? %>
    <section class="mt-5">
      <%= form_with(model: @product, local: true, method: :get, url: purchase_history_range_path) do |f| %>
        <div class="row">
          <div class="col-3">
            <div class="form-group">
              <%= f.label :start_date, "開始" %>
              <%= f.date_select :start_date, {use_month_numbers: true}, {class:'form-control bootstrap-date'} %>
            </div>
          </div>

          <div class="col-3">
            <div class="form-group">
              <%= f.label :end_date, "終了" %>
              <%= f.date_select :end_date, {use_month_numbers: true}, {class:'form-control bootstrap-date'} %>
            </div>
          </div>
          <%= f.submit "完了", class: "btn btn-info align-self-start" %>
        <div>
      <% end %>
    </section>
  <% end %>

  <table class= "table mt-4">
    <tr>
      <% if current_user.admin? %>
        <th>購入者</th>
      <% end %>
      <th>商品名</th>
      <th>購入数</th>
      <th>金額</th>
      <th>配達者ID</th>
      <th>購入日</th>
    </tr>

    <% @purchase_histories.each do |purchase_history| %>
      <tr>
        <% if current_user.admin? %>
          <td><%= purchase_history.user_name %></td>
        <% end %>
        <td><%= purchase_history.product_name %></td>
        <td><%= purchase_history.quantity %></td>
        <td>¥<%= purchase_history.price %></td>
        <td><%= purchase_history.delivery_user %></td>  
        <td><%= purchase_history.updated_at.strftime('%Y/%m/%d %H:%M') %></td>

      </tr>
    <% end %>
  </table>

  <%= paginate @purchase_histories %>

  <% if current_user.admin? %>
    <div class="text-right">
      <%= link_to "CSV出力", purchase_history_path(format: :csv), class: "btn btn-success mt-3" %>
    </div>
  <% end %>
</div>

<style>
.bootstrap-date {
  display: inline-block;
  width: auto;
}
</style>

app/views/purchase_histories/index.html.erb
<%= render 'csv' %>

app/views/purchase_histories/range.html.erb
<%= render 'csv' %>