config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/purchase_history', to: 'purchase_histories#index'
  get '/purchase_history/range', to: 'purchase_histories#range'
  # get '/purchase_history/:id', to: 'purchase_histories#show'

  post '/carts/add', to: 'carts#add'
  resources :carts, only: [:index, :edit, :update, :destroy]

  resources :products, only: [:show, :new, :create, :edit, :update, :destroy]
  
  resource :charge, only: [:create]
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products

  def total_price
    price_array = []
    products.zip(cart_products) do |cart_item, order_num|
      price_array.push(cart_item.price * order_num.quantity)
    end
    return price_array.sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :exist_cart, only:[:index]

  def index
    @cart_items = current_user.cart.products
    @order_nums = current_user.cart.cart_products
    @total_price = current_user.cart.total_price
  end

  def add
    if params[:cart_product][:quantity].to_i <= 0
      flash[:danger] = "購入数を0より大きい数で指定してください。"
      redirect_back(fallback_location: root_path) and return
    end
    if params[:cart_product][:product_num].to_i >= params[:cart_product][:quantity].to_i
      if current_user.cart.cart_products.find_by(product_id: params[:cart_product][:product_id])
        @cart_product = current_user.cart.cart_products.find_by(product_id: params[:cart_product][:product_id])
        @cart_product.quantity += params[:cart_product][:quantity].to_i
      else
        @cart_product = current_user.cart.cart_products.build(product_id: params[:cart_product][:product_id])
        @cart_product.quantity = params[:cart_product][:quantity].to_i
      end

      if @cart_product.save
        flash[:success] = "カートに追加しました。"
        redirect_to root_path
      else
        flash[:danger] = "カートの追加に失敗しました。"
        redirect_back(fallback_location: root_path)
      end
    else
      flash[:danger] = "在庫数より少ない数を指定してください。"
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @product = Product.find_by_hashid(params[:id])
    @cart_item = current_user.cart.products.find_by(id: @product.id)
    @cart = current_user.cart.cart_products.find_by(product_id: @product.id)
  end

  def update
    if params[:cart_product][:quantity].to_i <= 0
      flash[:danger] = "購入数を0より大きい数で指定してください。"
      redirect_back(fallback_location: root_path) and return
    end
    @cart_product = current_user.cart.cart_products.find_by(product_id: params[:cart_product][:product_id])
    @cart_item = current_user.cart.products.find_by(id: params[:cart_product][:product_id])
    if @cart_item.num >= params[:cart_product][:quantity].to_i
      @cart_product.quantity =  params[:cart_product][:quantity].to_i
      @cart_product.save
      flash[:success] = "購入数を変更しました。"
      redirect_to carts_path
    else
      flash[:danger] = "在庫数より少ない数を指定してください。"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @product = Product.find_by_hashid(params[:id])
    cart_product = current_user.cart.cart_products.find_by(product_id: @product.id)
    cart_product.destroy
    redirect_to carts_path
  end

  private

  def exist_cart
    unless current_user.cart
      @products = Product.all
      flash[:success] = "カートはからの状態です。"
      redirect_to root_path
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<div class="col-md-6 offset-md-3">
  <h2 class="text-center">購入数変更</h2>
  <section>
    <div class="p-4 text-center">
      <% if @cart_item.img? %>
        <%= image_tag @cart_item.img.url, alt: "書籍の画像です。", :width =>"100%" %>
      <% else %>
        <%= image_tag "no-img.png", alt: "画像が登録されていません。", :width =>"100%" %>
      <% end %>
    </div>
    <div class="pl-5">
      <div>タイトル: <%= @cart_item.name %></div>
      <div>著者: <%= @cart_item.author %></div>
      <div>価格: ¥<%= @cart_item.price %></div>
      <div>在庫数: <%= @cart_item.num %></div>
      <div>説明: <%= @cart_item.description %></div>

      <div>
        <%= form_with(model: @cart, url: cart_path, local: true ) do |f| %>
          <div>
            <%= f.label :quantity, "購入数" %>
            <%= f.number_field :quantity %>
          </div>
          <%= f.hidden_field :product_id, :value => @cart_item.id %>
          <div class="text-right">
            <%= f.submit "更新", class: "btn btn-info" %>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/carts/index.html.erb
<div class="col-md-8 offset-md-2">
  <h2 class="text-center">カート</h2>

  <% if @cart_items.blank? %>
    <p class="text-center mt-5">カートに商品はありません。</p>
  <% else %>

    <table class= "table">
      <% @cart_items.zip(@order_nums) do |cart_item, order_num| %>
        <tr>
          <td>タイトル: <%= cart_item.name %></td>
          <td>著者: <%= cart_item.author %></td>
          <td>価格: ¥<%= cart_item.price %></td>
          <td>購入数: <%= order_num.quantity %></td>
          <td>
            <%= link_to "変更", edit_cart_path(cart_item), class: "btn btn-edit btn-sm" %>
            <%= link_to "削除", cart_path(cart_item), class: "btn btn-delete btn-sm", method: :delete, data: { confirm: 'この商品を削除してもよろしいですか？' } %>
          </td>
        </tr>
      <% end %>
    </table>

    <div class="text-right">合計金額: <%= @total_price %> 円</div>

    <div>
      <%= form_with(url: :charge, method: :post) do |f| %>
        <div class="form-group col-md-6">
          <%= f.label :delivery_user, "配達者(ユーザーID)" %>
          <%= f.text_field :delivery_user, class: "form-control" %>
        </div>

        <%= f.hidden_field :product_ids, :value => @cart_items.ids.join(",") %>
        
        <div class="text-right">
        <script
          src="https://checkout.stripe.com/checkout.js"
          class="stripe-button"

          data-key=<%= Rails.configuration.stripe[:data_key] %>
          
          data-amount=<%= @total_price %>
          data-currency="jpy"
          data-name="Stripe.com"
          data-label="支払い画面へ" 
          data-description="Example charge"
          data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
          data-locale="auto">
        </script>
        </div>
      <% end %>
    </div>
  <% end %>
</div>