config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/purchase_history', to: 'purchase_histories#index'
  get '/purchase_history/range', to: 'purchase_histories#range'
  # get '/purchase_history/:id', to: 'purchase_histories#show'

  post '/carts/add', to: 'carts#add'
  resources :carts, only: [:index, :edit, :update, :destroy]

  resources :products, only: [:show, :new, :create, :edit, :update, :destroy]
  
  resource :charge, only: [:create]
  
end

app/models/product.rb
class Product < ApplicationRecord
  include Hashid::Rails
  mount_uploader :img, ImgUploader
  has_many :cart_products, dependent: :destroy
  has_many :purchase_history_products, dependent: :destroy
  validates :name, presence: true
  validates :author, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :num, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_admin, only: [:new, :create, :edit, :update, :destroy]
  
  def show
    @product = Product.find(params[:id])
    if current_user.cart.blank?
      cart = current_user.build_cart
      cart.save
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:success] = "登録に成功しました。"
      redirect_to @product
    else
      flash.now[:danger] = "登録に失敗しました。"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      flash[:success] = "商品情報を更新しました。"
      redirect_to @product
    else
      flash.now[:danger] = "商品情報の更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:success] = "削除しました。"
      redirect_to root_path
    else
      flash.now[:danger] = "削除に失敗しました。"
      render :show
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :author, :description, :price, :num, :img)
  end

  def confirm_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="col-md-6 offset-md-3">
  <h2 class="text-center">編集</h2>
  <ul>
    <%= form_with(model: @product, local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      <div>
        <%= f.label :name, "タイトル" %>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      <div>
        <%= f.label :author, "著者" %>
        <%= f.text_field :author, class:'form-control' %>
      </div>
      <div>
        <%= f.label :description, "内容" %>
        <%= f.text_area :description, class:'form-control' %>
      </div>
      <div>
        <%= f.label :price, "価格" %>
        <%= f.number_field :price, class:'form-control' %>
      </div>
      <div>
        <%= f.label :num, "数量" %>
        <%= f.number_field :num, class:'form-control' %>
      </div>
      <div>
        <%= f.label :img, "画像" %>
        <%= f.file_field :img %>
      </div>
      <div class="text-right">
        <%= f.submit "更新", class: "btn btn-info" %>
      </div>
    <% end %>
  </ul>
</div>

app/views/products/new.html.erb
<div class="col-md-6 offset-md-3">
  <h2 class="text-center">商品登録</h2>

  <ul>
    <%= form_with(model: @product, local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      <div class="form-group">
        <%= f.label :name, "タイトル" %>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :author, "著者" %>
        <%= f.text_field :author, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description, "内容" %>
        <%= f.text_area :description, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :price, "価格" %>
        <%= f.number_field :price, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :num, "数量" %>
        <%= f.number_field :num, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :img, "画像" %>
        <%= f.file_field :img %>
      </div>
      <div class="text-right">
        <%= f.submit "登録", class: "btn btn-info" %>
      </div>
    <% end %>
  </ul>
</div>

app/views/products/show.html.erb
<div class="col-md-6 offset-md-3">
  <h2 class="text-center">商品情報</h2>
  <div class="p-4 text-center">
    <% if @product.img? %>
      <%= image_tag @product.img.url, alt: "書籍の画像です。", :width => "100%" %>
    <% else %>
      <%= image_tag "no-img.png", alt: "画像が登録されていません。", :width => "100%" %>
    <% end %>
  </div>
  <div class="pl-5">
    <div>タイトル: <%= @product.name %></div>
    <div>著者: <%= @product.author %></div>
    <div>価格: ¥<%= @product.price %></div>
    <div>在庫数: <%= @product.num %></div>
    <div>説明: <%= @product.description %></div>

    <% unless current_user.admin? %>
      <div>
        <%= form_with(model: current_user.cart.cart_products.build, url: carts_add_path, local: true ) do |f| %>
          <%= render "layouts/error_messages", model: f.object %>
          <div class="form-group">
            <%= f.label :quantity, "購入数" %>
            <%= f.number_field :quantity, :value => 1 %>
          </div>
          <%= f.hidden_field :product_id, :value => @product.id %>
          <%= f.hidden_field :product_num, :value => @product.num %>
          <div class="text-right">
            <%= f.submit "カートに入れる", class: "btn btn-info" %>
          </div>
        <% end %>
      </div>
    <% else %>
      <section class="text-right py-3">
        <%= link_to "編集", edit_product_path(@product), class: "btn btn-edit"%>
        <%= link_to '削除', product_path(@product), class: "btn btn-delete", method: :delete, data: { confirm: "削除してもよろしいですか？"}  %>
      </section>
    <% end %>
  </div>
</div>