config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/purchase_history', to: 'purchase_histories#index'
  get '/purchase_history/range', to: 'purchase_histories#range'
  # get '/purchase_history/:id', to: 'purchase_histories#show'

  post '/carts/add', to: 'carts#add'
  resources :carts, only: [:index, :edit, :update, :destroy]

  resources :products, only: [:show, :new, :create, :edit, :update, :destroy]
  
  resource :charge, only: [:create]
  
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand navbar-light p-4">
    <%= link_to "NeighBook", root_path, class: 'navbar-brand ml-5 brand-size' %>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <%= link_to current_user.name, edit_user_registration_path, class: 'nav-link' %>
          <% unless current_user.admin? %>
            <%= link_to "カート", carts_path, class: 'nav-link' %>
          <% end %>
          <%= link_to "注文履歴", purchase_history_path, class: 'nav-link' %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% else %>
          <%= link_to "ユーザー登録", new_user_registration_path, class: 'nav-link' %>
          <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NeighBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <div class="row">
      <%= yield %>
    </div> 
  </body>
</html>